stages:
  - lint
  - test

variables:
  DATABASE_URL: "sqlite:///test.db"

# Проверить на ветке пуш. либо прописывать ветки каждый раз, иначе на других ветках при пуше будет срабатывать
pre-commit:
  stage: lint
  image: python:3.11
  script:
    - cd Group4
    - pre-commit run --all-files
  only:
    - CI/CD.test_runner
    - master/messages

tests:
  stage: test
  services:
    - postgres:latest
  variables:
    POSTGRES_DB: test_db
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/test_db"
  before_script:
    - pip install -r Group4/requirements.txt
    - cd Group4
    - sleep 5
    - python init_db.py || true
    - uvicorn main:app --host 0.0.0.0 --port 8000 &
    - sleep 10
  script:
    - pytest tests/ -v
  only:
    - CI/CD.test_runner
    - master/messages